version: '3.9'

services:
   web:
      build: .
      command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
      ports:
         - 8000:8000
      volumes:
         - .:/app

   dev-db:
      image: postgres:17.0
      restart: always
      ports:
         - "5433:5432"
      env_file:
         - ./.env
      volumes:
         - ./scripts:/docker-entrypoint-initdb.d

   adminer:
      image: adminer
      restart: always
      ports:
         - 8080:8080

name: idky-delevopment